# Generated by Django 6.0.4 on 2026-05-02 20:35

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='technical_sheet',
            field=models.FileField(blank=True, help_text='Ficha técnica en PDF', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='products/docs/'),
        ),
    ]
