# Generated by Django 6.0.2 on 2026-02-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='material_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Cliente'), ('supplier', 'Proveedor'), ('admin', 'Administrador')], default='client', max_length=20),
        ),
    ]
