# Generated by Django 6.0.4 on 2026-05-22 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_technical_sheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Platform fee percentage for this supplier', max_digits=5),
        ),
        migrations.AddField(
            model_name='supplier',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account ID (acct_xxxxx)', max_length=255),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.PositiveIntegerField(help_text='Total charged to buyer in cents')),
                ('application_fee', models.PositiveIntegerField(help_text='Platform fee in cents')),
                ('supplier_payout', models.PositiveIntegerField(help_text='Amount supplier receives in cents')),
                ('stripe_checkout_session_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='home.conversation')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='home.quoterequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
