# Generated by Django 6.0.3 on 2026-03-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_productcategory_quoterequest_client_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='material_category',
            field=models.CharField(blank=True, choices=[('paint', 'Pintura'), ('steel', 'Acero'), ('cement', 'Cemento')], max_length=100, null=True),
        ),
    ]
