# Generated by Django 6.0.3 on 2026-03-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_userprofile_material_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('paint', 'Pintura'), ('steel', 'Acero'), ('cement', 'Cemento'), ('aluminum', 'Aluminio'), ('glass', 'Vidrio')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría de Proveedor',
                'verbose_name_plural': 'Categorías de Proveedores',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='material_category',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='material_categories',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='home.suppliercategory'),
        ),
    ]
