# Generated by Django 6.0.3 on 2026-03-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_suppliercategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='catalog_pdf',
            field=models.FileField(blank=True, help_text='Catálogo del proveedor en PDF (opcional)', null=True, upload_to='catalogs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Número internacional sin espacios ni símbolos, ej: 521234567890', max_length=20),
        ),
    ]
